### ISSUE TITLE
Corrigir layout (alinhamentos, h1, h2, etc)

### ISSUE THREAD

**Issue by giggio** [diversidade/diversidade.github.io#12]
Os documentos estão ficando quebrados. Os h1, h2, h3, etc estão encavalando. Parece que `texto de código`pode estar quebrado também.

Exemplo, esse código em markdown:

````markdown
## Sobre esse exemplo de código de conduta

O exemplo a seguir pode ser utilizado como base para o código de conduta da sua
empresa, evento, ou qualquer outro tipo de associação. Os pontos do texto que
você precisa substituir estão marcados entre colchetes `[]`.

O código inicia com um [TLDR](https://en.wikipedia.org/wiki/TL;DR), é então
detalhado, e por fim é discutido seu licenciamento.

`Início do código de conduta`

## Código de conduta

### TL;DR

Esperamos que você se comporte. Que respeite as pessoas à sua volta. Que não exclua pessoas com base nas suas origens, comportamentos, ou atributos. Que não faça comentários agressivos de qualquer natureza. Se isso acontecer nós iremos lhe avisar, se acontecer de forma reiterada nós iremos lhe remover, e você está de acordo com isso.
````

Está resultando nesta imagem:

![image](https://user-images.githubusercontent.com/334958/30505554-c40dce90-9a4b-11e7-850b-42a6eae7bc58.png)

**Comment by lucasvsme** [comment]
@giggio Alterei o CSS do template pra resolver esse problema da mistura das linhas. (1e1eb5c)

![screenshot from 2017-09-24 23-38-12](https://user-images.githubusercontent.com/10524730/30790327-b1f8671e-a181-11e7-8a1d-547ef139cc5a.png)

[Aqui](https://user-images.githubusercontent.com/10524730/30790311-9d0266c0-a181-11e7-92bc-2c076801a9f2.png) tem outra screenshot mostrando mais estruturas de Markdown depois da alteração também.

Se tiver tudo certo me avisa que mando o pull request. :+1:

**Comment by giggio** [comment]
Fechado no #14.
